FROM golang:latest

WORKDIR /home/link_service

ADD ./main.go main.go
ADD ./go.mod go.mod
ADD ./service service

# Fetch dependencies
ENV GOPROXY https://goproxy.cn
ENV GO111MODULE on
RUN go mod tidy

#Build image as a truly static Go binary 
RUN CGO_ENABLED=0 GOOS=linux go build -o /link_service -a -tags netgo -ldflags '-s -w' .

EXPOSE 8080
ENTRYPOINT ["/link_service"]
