FROM golang:latest

RUN git clone -b lm github.com/pingguodeli573365/delinkcious

WORKDIR /go/src/github.com/pingguodeli573365/delinkcious/svc/social_graph_service

RUN CGO_ENABLED=0 GOOS=linux go build -o /social_graph_service -a -tags netgo -ldflags '-s -w' .

EXPOSE 8080
ENTRYPOINT ["/social_graph_service"]
